# inventories/staging/hosts.yml
all:
  vars:
    ansible_ssh_private_key_file: /Users/eep/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:
    app_servers:
      hosts:
        vm-app:
          ansible_user: eep-vm-app  # <-- ganti dengan username VM kamu
          ansible_host: 103.217.144.152   # <-- ganti IP VM app kamu
          server_role: app

    gateway_servers:
      hosts:
        vm-gateway:
          ansible_user: eep-vm-gateway  # <-- ganti dengan username VM kamu
          ansible_host: 116.193.191.28   # <-- ganti IP VM gateway kamu
          server_role: gateway